//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group11_007_iCAREAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group11_007_iCAREDBEntities1 : DbContext
    {
        public Group11_007_iCAREDBEntities1()
            : base("name=Group11_007_iCAREDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentMetadata> DocumentMetadata { get; set; }
        public virtual DbSet<DrugDictionary> DrugDictionary { get; set; }
        public virtual DbSet<GeoCodes> GeoCodes { get; set; }
        public virtual DbSet<iCare_Admin> iCare_Admin { get; set; }
        public virtual DbSet<iCare_Worker> iCare_Worker { get; set; }
        public virtual DbSet<iCareUser> iCareUser { get; set; }
        public virtual DbSet<PatientRecord> PatientRecord { get; set; }
        public virtual DbSet<TreatmentRecord> TreatmentRecord { get; set; }
        public virtual DbSet<UserPassword> UserPassword { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<ModificationHistory> ModificationHistory { get; set; }
    }
}
